FROM python:3.6-alpine as dependencies

COPY ./requirements.txt .

RUN apk add --update --no-cache python3-dev build-base && pip install -r requirements.txt

FROM python:3.6-alpine

WORKDIR /usr/src/app

ENV GOOGLE_APPLICATION_CREDENTIALS="API_KEY.json" \
    FLASK_APP="app" \
    FLASK_RUN_HOST="0.0.0.0"

COPY --from=dependencies /root/.cache /root/.cache
COPY --chown=1000:1000 ./ ./

RUN addgroup -S worker && adduser -S worker -G worker && chown -R worker:worker /usr/src/app \
&& pip install -r requirements.txt \
&& apk add --no-cache ffmpeg \
&& rm -rf /root/.cache \
&& rm -rf /var/cache/apk/* /tmp/*


USER worker

CMD python -u -m flask run